---
version: '3.9'
services:
    redis:
        image: redis:latest
        expose:
          - 6379:6379
        volumes:
          - cache:/data

    app:
        build:
            context: .
            args:
                INSTALL_DEPENDENCIES: dev
        depends_on:
            redis:
                condition: service_started

        ports:
          - 8000:8000
        env_file:
          - .env
        volumes:
          - .:/app:cached

volumes:
    cache: {}
